version: '3.8'

services:
  postgres:
    container_name: voice-postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=voice_analytics
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d voice_analytics"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - voice-network
    command: postgres -c 'max_connections=200'

  redis:
    container_name: voice-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - voice-network

networks:
  voice-network:
    name: voice-network
    driver: bridge

volumes:
  postgres_data:
    name: voice-postgres-data
  redis_data:
    name: voice-redis-data 